### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by ghost** [LuukNoverraz/Python-4#1]
Bij het runnen van de main.py krijg ik de volgende melding:
- keuze 1
  File "main.py", line 163, in <module>
    main()
  File "main.py", line 155, in main
    elif userInput == "4" or userInput.upper() == "QQ":
AttributeError: 'int' object has no attribute 'upper'

**Comment by LuukNoverraz** [comment]
Ik heb zelf niet de error, maar als ik er zo naar kijk ligt het aan dat hij ook upper op 4 doet en 4 als int wordt geclassificeerd. Dus ik heb str() op 4 gezet en ik _denk_ dat hij nu werkt. Maar ik kan het dus niet echt uittesten :/
